services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest # SQL Server 2022 (v16)
    container_name: tce-bpmn-sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
